version: 2

before:
  hooks:
  - go mod tidy
  - go test ./...

builds:
- id: sportsagent
  main: ./main.go
  binary: sportsagent
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  ldflags:
  - -s -w
  - -X sportsagent/internal/version.BuildVersion={{.Version}}
  - -X sportsagent/internal/version.Commit={{.Commit}}
  - -X sportsagent/internal/version.Date={{.Date}}
  ignore:
  - goos: windows
    goarch: arm64

archives:
- id: default
  format: tar.gz
  name_template: >-
    {{ .ProjectName }}_ {{- .Version }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }}
  format_overrides:
  - goos: windows
    format: zip
  files:
  - README.md
  - LICENSE*

checksum:
  name_template: 'checksums.txt'

changelog:
  skip: true # We use semantic-release for changelog

release:
  github:
    owner: maxo99
    name: go-sportsagent
  draft: false
  prerelease: auto
  mode: append
  name_template: "{{.Tag}}"
